language:
- objective-c

env:
  global:
    - MPL_COMMIT=latest-tag
    - FT_VERSION=2.5.3
    - PNG_VERSION=1.6.12
    - ZLIB_VERSION=1.2.8
    - TCL_URL=http://downloads.activestate.com/ActiveTcl/releases
    # Need to check these last two from time to time
    - TCL_VERSION=8.5.17.0
    - TCL_DMG=ActiveTcl8.5.17.0.298612-macosx10.5-i386-x86_64-threaded.dmg
  matrix:
  - VERSION=2.7.9 NUMPY_VERSION=1.6.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.2 NUMPY_VERSION=1.7.1

install:
# increase number of open files allowed for tests
# https://github.com/matplotlib/matplotlib/issues/3315
- ulimit -n 4096
- source run_install.sh
- get_python_environment macpython $VERSION venv
- check_var $BUILD_PREFIX
- check_var $SYS_CC
- check_var $SYS_CXX
- check_var $PYTHON_EXE
- ls
- cd pywikibot-core
- echo '[directories]' >> setup.cfg
- echo "basedirlist = $BUILD_PREFIX, /usr" >> setup.cfg
- CC=${SYS_CC} CXX=${SYS_CXX} python setup.py bdist_wheel
- pip install dist/*.whl

script:
# Fix numpy ast errors in tests by upgrading numpy
- $PYTHON_EXE setup.py test
